get http://localhost:3000/players/

###
POST http://localhost:3000/players/
Content-Type: application/json

{
 "playerName":"Vishal",
 "jerseyNumber":17,
 "role":"Bowler"
}

###
get http://localhost:3000/players/11/

###
put http://localhost:3000/players/5/
Content-Type: application/json

{
 "playerName":"khajarasool",
 "jerseyNumber":22,
 "role":"Bowler"
}

###
delete http://localhost:3000/players/5/
